### ISSUE TITLE
Blank screen after initial set-up

### ISSUE THREAD

**Issue by looowizz** [YunoHost-Apps/feber_ynh#4]
Hi there!

I'm having an issue with feber on my Yunohost instance. These are the details of the instance:

- Server hardware architecture is i386
- Server is running Linux kernel 5.10.0-32-686-pae
- Server is running Debian 11.10
- Server is running YunoHost 11.2.28 (stable)

After creating the calendar and setting up the admin credentials then signing in with those credentials, I receive a blank webpage and nothing loads :/

This is the log for nginx which is the only relevant log i found on the Yunohost admin page: https://paste.yunohost.org/doniqusanu.yaml.

Hope someone can help and happy to provide any extra information :)

**Comment by OniriCorpe** [comment]
Looking at this tomorrow (if I don’t forget (as usual))

**Comment by looowizz** [comment]
tysm!

**Comment by OniriCorpe** [comment]
i'm not able to reproduce...

i tried from the root of a domain name (test.example.com)
from a path (test.example.com/feber)

with a lowercase username, uppercase username, a combination of uppercase and lowercase letters, without success

everything is working like a charm on my side

will send the link to this issue to the feber dev, maybe they will have an idea ..?

**Comment by looowizz** [comment]
Thank you for trying and contacting the dev!

I just tried it on another web server I have access to and it worked perfectly as well.

Also, I tried using [this Yunohost app](https://github.com/YunoHost-Apps/my_webapp_ynh) and uploading the Feber files directly to see if it was an issue with the package or my server and it seems my server is the issue as it still is doing the same thing :/.

My server is a 16 year old laptop so I'm surprised its running anything at all haha

**Comment by OniriCorpe** [comment]
maybe it's a dependency issue?
i mean, maybe my server and your working server have a php dependency which is lacking from your non-working server?

the yunohost package only list `php8.3-fpm` as a dependency, but maybe another one is needed? i see nothing about this on the dev's website, but that's my intuition

```toml
    [resources.apt]
    packages = "php8.3-fpm"
```

**Comment by simonrepp** [comment]
Hey everyone!

Reading @OniriCorpe's last comment I immediately remembered there was something I stumbled over a few weeks back, and I found it in my todo list:

> - Add to gotchas:
>   Fatal error: Call to undefined function: mb_strtolower() in ????.php on line ?? ----->   php-mbstring extension needed

And indeed this seems to be the culprit here as well according to the log:

> 2024/08/27 23:22:47 [error] 6840#6840: *94 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mb_strtolower() in /var/www/feber/index.php:1878

So I think adding this dependency to the yunohost package should do the trick!

Thanks to both of you for reporting and hints (with lots of details too <3) and pinging me about this!

I'll get this info added to the feber website as well asap.

**Comment by simonrepp** [comment]
One more thing: I will additionally add a runtime check on the calendar setup page that catches if `mbstring` is not enabled, and give a helpful hint about that (instead of just crashing on the next page :)).

**Comment by simonrepp** [comment]
I added the mbstring dependency info to the feber website and released 1.1.2 which includes a runtime check for this in the setup (attached how it now looks when the dependency is missing).

Oh and I noticed that I apparently had forgotten to push the (already existing) tags for all previous releases and fixed that, so starting now feber can also be obtained as a tarball from codeberg if that is more convenient for packaging or such: https://codeberg.org/simonrepp/feber/tags

![feber_mbstring_check](https://github.com/user-attachments/assets/47f14f0b-7392-4fc8-a252-cb695f99de3b)

**Comment by looowizz** [comment]
Woo! That was exactly it, thank you!

For me, mbstring was installed for a different version of php so i ran `sudo apt-get install php8.3-mbstring` then restarted the php8.3-fpm service and everything worked great :)

**Comment by OniriCorpe** [comment]
great, thanks for the quick fix release!!

i created a PR: #5 

> so starting now feber can also be obtained as a tarball from codeberg if that is more convenient for packaging or such

yes it is! now i can activate the autoupdate mechanism, so the package will be automatically updated to the newest version when there is a new release!
